### ISSUE TITLE
Can't load a pandas dataframe into a Bach dataframe if there are `None` values in text columns

### ISSUE THREAD

**Issue by hendrik-obj** [objectiv/objectiv-analytics#418]
**Issue:** Loading a pandas frame to a Bach dataframe does not work if there are text columns with missing data (`None` values).

Loading text data from pandas only works when `convert_objects=True` is used. This converts `None` values in text columns to values of `pandas._libs.missing.NAType` type, which is currently not supported by Bach.

**Comment by thijs-obj** [comment]
@hendrik-obj can you shed some more light on what exactly the issue is here? Perhaps a code example.

Maybe related: I noticed that in all cases in Bach and Modelhub we set `convert_objects=True`. The only cases where it is `False` are tests that explicitly test that behaviour. **Question:** should we make `convert_objects=True`  the default? Maybe even remove the option?

**Comment by thijs-obj** [comment]
Assigned the issue to you @hendrik-obj as we need some input from you. Feel free to assign it afterwards to me or un-assign it

**Comment by hendrik-obj** [comment]
> Assigned the issue to you @hendrik-obj as we need some input from you. Feel free to assign it afterwards to me or un-assign it

This issue can be closed. Works now. `convert_objects=True` sounds like a good idea, as it is most fool proof. 

The reason the parameter exists is that it can be a bit faster for big data frames if `convert_objects=False` for which it is not needed to convert objects. However it is not really tested how much `convert_objects` affects performance and perhaps it is better to be removed.

**Comment by thijs-obj** [comment]
Thanks for checking. Created a new issue for the conver_objects parameter: https://github.com/objectiv/objectiv-analytics/issues/1405
